# Generated by Django 5.2.4 on 2025-08-03 05:42

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Record',
            fields=[
                ('record_id', models.IntegerField(primary_key=True, serialize=False)),
                ('view_id', models.IntegerField()),
                ('published_date', models.DateTimeField()),
            ],
        ),
        migrations.CreateModel(
            name='AgendaItem',
            fields=[
                ('agenda_id', models.UUIDField(primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=256)),
                ('start_time', models.IntegerField()),
                ('end_time', models.IntegerField()),
                ('summary', models.TextField()),
                ('transcript', models.TextField()),
                ('record', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='agenda_items', to='transcripts_api.record')),
            ],
        ),
    ]
