# Generated by Django 5.2.4 on 2025-08-03 16:53

import pgvector.django.vector
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("transcripts_api", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="agendaitem",
            name="embeddings",
            field=pgvector.django.vector.VectorField(blank=True, null=True),
        ),
    ]
